### ISSUE TITLE
Tiến độ hoàn thành

### ISSUE THREAD

**Issue by molr298** [yul1492101/Project_IntroDS#1]
Code bài làm được lưu tại file Final-T.ipynb.
Các mục đã hoàn thành:

> Khám phá và tìm hiểu sơ lược về dữ liệu - Hoàn thành 

> Tiền xử lí dữ liệu - Hoàn thành

> Đặt các câu hỏi - Hoàn thành

> Trả lời câu hỏi - Hoàn thành

Đánh giá mức độ hoàn thành: 100%

**Comment by HMy2912** [comment]
Xin chào nhóm 15, mình là Hoàn Mỹ từ nhóm 14,

Sau khi xem qua bài làm của các bạn thì mình có những chia sẻ sau:

* Phần tiền xử lý các bạn đã làm kĩ và mình nghĩ thấy ổn ở phần này.
* Phần câu hỏi, vì motif hai câu hỏi giống nhau và mình cũng không chắc là điều này có lợi cho bài làm của nhóm bạn.
- Mình thấy câu 1 của hai bạn chưa hoàn thành; chỉ có biểu đồ cột thôi, mình nghĩ các bạn có thể dùng những loại biểu đồ khác như pie chẳng hạn (so sánh phần % giữa các thành phần ...)
- Mình thấy có phần các bạn đếm số lượng thì có thể trình bày thông qua stacked bar chart hoặc một hình thức khác, để có thể thuận tiện theo dõi hơn, thay vì list ra số trong DataFrame như vậy.
- Và bạn chưa nhận xét gì về câu 1 nên mình sẽ không nhận xét phần này.
- Câu 2 thì mình thấy các bạn làm tốt hơn, tuy rằng trên Github không thể hiện ra chart nhưng mình thấy các bạn cũng dùng đa dạng biểu đồ hơn và trả lời khá tốt, liền mạch.

Cám ơn nhóm 15, chúc các bạn sẽ hoàn thành tốt môn học ✨

**Comment by quocPhat1902** [comment]
Xin chào nhóm 15, Mình là Phát đến từ nhóm 14.
Sau khi xem qua bài của các bạn mình có những chia sẻ sau:
+ Phần tiền xử lý các bạn làm rất chặt chẽ và rất tốt.
+ Nhưng mình nghĩ ở câu 1, nếu các bạn dùng những loại biểu đồ khác để trực quan thì sẽ tốt hơn vì người đọc sẽ không đánh giá nhanh được số liệu .
+ Câu 2 tuy các bạn không thể hiện chart nhưng số liệu rất tường minh.
Cám ơn nhóm 15, chúc các bạn đạt điểm cao nhé
